export const FETCHING_STORES = 'FETCHING_STORES';
export const FETCHING_STORES_FAILURE = 'FETCHING_STORES_FAILURE';
export const FETCHING_STORES_SUCCESS = 'FETCHING_STORES_SUCCESS';

export const CREATING_SHOPPING_LIST = 'CREATING_SHOPPING_LIST';
export const CREATING_SHOPPING_LIST_FAILURE = 'CREATING_SHOPPING_LIST_FAILURE';
export const CREATING_SHOPPING_LIST_SUCCESS = 'CREATING_SHOPPING_LIST_SUCCESS';