// export const FETCHING_COIN_DATA = 'FETCHING_COIN_DATA';
// export const FETCHING_COIN_DATA_FAILURE = 'FETCHING_COIN_DATA_FAILURE';
// export const FETCHING_COIN_DATA_SUCCESS = 'FETCHING_COINT_DATA_SUCCESS';

export const FETCHING_STORES = 'FETCHING_STORES';
export const FETCHING_STORES_FAILURE = 'FETCHING_STORES_FAILURE';
export const FETCHING_STORES_SUCCESS = 'FETCHING_STORES_SUCCESS';

export const CREATE_SHOPPING_LIST = 'CREATE_SHOPPING_LIST';