export const FETCHING_COIN_DATA = 'FETCHING_COIN_DATA';
export const FETCHING_COIN_DATA_FAILURE = 'FETCHING_COIN_DATA_FAILURE';
export const FETCHING_COIN_DATA_SUCCESS = 'FETCHING_COINT_DATA_SUCCESS';

export const CREATE_SHOPPING_LIST = 'CREATE_SHOPPING_LIST';